spring:
  datasource:
      username: root
      password: Password
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sakila?useSSL=false
  show-sql: true
  jpa:
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
      org:
          hibernate:
              SQL: DEBUG
              type:
                  descriptor:
                      sql:
                          BasicBinder: TRACE