/**
 * This class is generated by jOOQ
 */
package com.excelian.comparison.db.jooq.entities.world.tables;


import com.excelian.comparison.db.jooq.entities.world.Keys;
import com.excelian.comparison.db.jooq.entities.world.World;
import com.excelian.comparison.db.jooq.entities.world.enums.CountrylanguageIsofficial;
import com.excelian.comparison.db.jooq.entities.world.tables.records.CountrylanguageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countrylanguage extends TableImpl<CountrylanguageRecord> {

    private static final long serialVersionUID = 1398027342;

    /**
     * The reference instance of <code>world.countrylanguage</code>
     */
    public static final Countrylanguage COUNTRYLANGUAGE = new Countrylanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountrylanguageRecord> getRecordType() {
        return CountrylanguageRecord.class;
    }

    /**
     * The column <code>world.countrylanguage.CountryCode</code>.
     */
    public final TableField<CountrylanguageRecord, String> COUNTRYCODE = createField("CountryCode", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>world.countrylanguage.Language</code>.
     */
    public final TableField<CountrylanguageRecord, String> LANGUAGE = createField("Language", org.jooq.impl.SQLDataType.CHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>world.countrylanguage.IsOfficial</code>.
     */
    public final TableField<CountrylanguageRecord, CountrylanguageIsofficial> ISOFFICIAL = createField("IsOfficial", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.excelian.comparison.db.jooq.entities.world.enums.CountrylanguageIsofficial.class), this, "");

    /**
     * The column <code>world.countrylanguage.Percentage</code>.
     */
    public final TableField<CountrylanguageRecord, Double> PERCENTAGE = createField("Percentage", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.0", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * Create a <code>world.countrylanguage</code> table reference
     */
    public Countrylanguage() {
        this("countrylanguage", null);
    }

    /**
     * Create an aliased <code>world.countrylanguage</code> table reference
     */
    public Countrylanguage(String alias) {
        this(alias, COUNTRYLANGUAGE);
    }

    private Countrylanguage(String alias, Table<CountrylanguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Countrylanguage(String alias, Table<CountrylanguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return World.WORLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CountrylanguageRecord> getPrimaryKey() {
        return Keys.KEY_COUNTRYLANGUAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CountrylanguageRecord>> getKeys() {
        return Arrays.<UniqueKey<CountrylanguageRecord>>asList(Keys.KEY_COUNTRYLANGUAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CountrylanguageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CountrylanguageRecord, ?>>asList(Keys.COUNTRYLANGUAGE_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Countrylanguage as(String alias) {
        return new Countrylanguage(alias, this);
    }

    /**
     * Rename this table
     */
    public Countrylanguage rename(String name) {
        return new Countrylanguage(name, null);
    }
}
