/**
 * This class is generated by jOOQ
 */
package com.excelian.comparison.db.jooq.entities.world;


import com.excelian.comparison.db.jooq.entities.world.tables.City;
import com.excelian.comparison.db.jooq.entities.world.tables.Country;
import com.excelian.comparison.db.jooq.entities.world.tables.Countrylanguage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in world
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>world.city</code>.
     */
    public static final City CITY = com.excelian.comparison.db.jooq.entities.world.tables.City.CITY;

    /**
     * The table <code>world.country</code>.
     */
    public static final Country COUNTRY = com.excelian.comparison.db.jooq.entities.world.tables.Country.COUNTRY;

    /**
     * The table <code>world.countrylanguage</code>.
     */
    public static final Countrylanguage COUNTRYLANGUAGE = com.excelian.comparison.db.jooq.entities.world.tables.Countrylanguage.COUNTRYLANGUAGE;
}
