/**
 * This class is generated by jOOQ
 */
package com.excelian.comparison.db.jooq.entities.tables;


import com.excelian.comparison.db.jooq.entities.Sakila;
import com.excelian.comparison.db.jooq.entities.tables.records.SalesByStoreRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByStore extends TableImpl<SalesByStoreRecord> {

    private static final long serialVersionUID = -399350289;

    /**
     * The reference instance of <code>sakila.sales_by_store</code>
     */
    public static final SalesByStore SALES_BY_STORE = new SalesByStore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesByStoreRecord> getRecordType() {
        return SalesByStoreRecord.class;
    }

    /**
     * The column <code>sakila.sales_by_store.store</code>.
     */
    public final TableField<SalesByStoreRecord, String> STORE = createField("store", org.jooq.impl.SQLDataType.VARCHAR.length(101), this, "");

    /**
     * The column <code>sakila.sales_by_store.manager</code>.
     */
    public final TableField<SalesByStoreRecord, String> MANAGER = createField("manager", org.jooq.impl.SQLDataType.VARCHAR.length(91), this, "");

    /**
     * The column <code>sakila.sales_by_store.total_sales</code>.
     */
    public final TableField<SalesByStoreRecord, BigDecimal> TOTAL_SALES = createField("total_sales", org.jooq.impl.SQLDataType.DECIMAL.precision(27, 2), this, "");

    /**
     * Create a <code>sakila.sales_by_store</code> table reference
     */
    public SalesByStore() {
        this("sales_by_store", null);
    }

    /**
     * Create an aliased <code>sakila.sales_by_store</code> table reference
     */
    public SalesByStore(String alias) {
        this(alias, SALES_BY_STORE);
    }

    private SalesByStore(String alias, Table<SalesByStoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private SalesByStore(String alias, Table<SalesByStoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sakila.SAKILA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalesByStore as(String alias) {
        return new SalesByStore(alias, this);
    }

    /**
     * Rename this table
     */
    public SalesByStore rename(String name) {
        return new SalesByStore(name, null);
    }
}
