/**
 * This class is generated by jOOQ
 */
package com.excelian.comparison.db.jooq.entities.sys.tables;


import com.excelian.comparison.db.jooq.entities.sys.Sys;
import com.excelian.comparison.db.jooq.entities.sys.tables.records.UserSummaryByFileIoRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSummaryByFileIo extends TableImpl<UserSummaryByFileIoRecord> {

    private static final long serialVersionUID = 1572250035;

    /**
     * The reference instance of <code>sys.user_summary_by_file_io</code>
     */
    public static final UserSummaryByFileIo USER_SUMMARY_BY_FILE_IO = new UserSummaryByFileIo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSummaryByFileIoRecord> getRecordType() {
        return UserSummaryByFileIoRecord.class;
    }

    /**
     * The column <code>sys.user_summary_by_file_io.user</code>.
     */
    public final TableField<UserSummaryByFileIoRecord, String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>sys.user_summary_by_file_io.ios</code>.
     */
    public final TableField<UserSummaryByFileIoRecord, BigInteger> IOS = createField("ios", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

    /**
     * The column <code>sys.user_summary_by_file_io.io_latency</code>.
     */
    public final TableField<UserSummaryByFileIoRecord, String> IO_LATENCY = createField("io_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>sys.user_summary_by_file_io</code> table reference
     */
    public UserSummaryByFileIo() {
        this("user_summary_by_file_io", null);
    }

    /**
     * Create an aliased <code>sys.user_summary_by_file_io</code> table reference
     */
    public UserSummaryByFileIo(String alias) {
        this(alias, USER_SUMMARY_BY_FILE_IO);
    }

    private UserSummaryByFileIo(String alias, Table<UserSummaryByFileIoRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserSummaryByFileIo(String alias, Table<UserSummaryByFileIoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSummaryByFileIo as(String alias) {
        return new UserSummaryByFileIo(alias, this);
    }

    /**
     * Rename this table
     */
    public UserSummaryByFileIo rename(String name) {
        return new UserSummaryByFileIo(name, null);
    }
}
